### ISSUE TITLE
Potential error in the dependecies

### ISSUE THREAD

**Issue by mastong** [sevaa-group/hubot-gitlab#2]
Hi,

I've  got an error when I try to use your module, saying that it can't find the module Gitlab.

I investigate your code and I think that it's an error in your depenencies in your package.json.
You currently use:
`"node-gitlab": "^1.2.1"`
And by looking at your code, I think your referring to this module [(https://github.com/node-gitlab/node-gitlab)]

But in fact, your loading this one [https://github.com/repo-utils/gitlab]

From what I understand, the project called node-gitlab on github must be called with "gitlab" in the dependencies.
And the project called gitlab on github must be called with "node-gitlab" in the dependencies.

I'm I right ? or did I misunderstood the issue ?

FYI, the modification in the dependencies allows me to start Hubot.

**Comment by RandallKent** [comment]
Hey @mastong! It sounds like you might be on to something :)

Can you post the error your receiving?

**Comment by mastong** [comment]
This is the error I get when I use the standard installation :

```
[Fri Mar 11 2016 17:39:01 GMT+0100 (CET)] INFO Slack client now connected
[Fri Mar 11 2016 17:39:01 GMT+0100 (CET)] ERROR Unable to load /opt/hubot/shirka/node_modules/hubot-gitlab/src/gitlab: Error: Cannot find module 'gitlab'
  at Function.Module._resolveFilename (module.js:339:15)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.<anonymous> (/opt/hubot/shirka/node_modules/hubot-gitlab/src/gitlab.coffee:20:11, <js>:4:13)
  at Object.<anonymous> (/opt/hubot/shirka/node_modules/hubot-gitlab/src/gitlab.coffee:20:1, <js>:118:4)
  at Module._compile (module.js:413:34)
  at Object.loadFile (/opt/hubot/shirka/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
  at Module.load (/opt/hubot/shirka/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Robot.loadFile (/opt/hubot/shirka/node_modules/hubot/src/robot.coffee:355:9, <js>:224:20)
  at module.exports (/opt/hubot/shirka/node_modules/hubot-gitlab/index.coffee:11:9, <js>:24:31)
  at Robot.loadExternalScripts (/opt/hubot/shirka/node_modules/hubot/src/robot.coffee:401:11, <js>:272:39)
  at /opt/hubot/shirka/node_modules/hubot/bin/hubot:119:11, <js>:126:26
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

I can avoid it by ;
- installing gitlab with `npm install gitlab --save`
- replacing in your package.json `"node-gitlab": "^1.2.1"` by `"gitlab": "^1.2.1"`

**Comment by RandallKent** [comment]
Nice - Can you submit a PR?

**Comment by ryansouthern** [comment]
#3 merged!
